# Generated by Django 6.0.3 on 2026-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnthusiasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('knows_emerging_artist', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('artist_details', models.CharField(blank=True, max_length=500, null=True)),
                ('discover_art', models.CharField(max_length=500)),
            ],
        ),
    ]
